### ISSUE TITLE
kScript is not defined

### ISSUE THREAD

**Issue by shamur** [gfxfundamentals/webgl2-fundamentals#160]
**Describe the bug**
```
Uncaught (in promise) ReferenceError: kScript is not defined
    at editor.js:315:37
    at String.replace (<anonymous>)
    at parseHTML (editor.js:313:15)
    at async main (editor.js:403:3)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/17883846/156688841-bda6caf0-0e4f-49ea-b793-0e74dd3e587a.png)

**Desktop**
 - OS: MacOS Monterey
 - Browser Chrome
 - Version 99.0.4844.51 (Official Build) (x86_64)

**Additional context**
Pretty nice work by the way, thank you so much, i am learning a lot from this site. 👍🏻

**Comment by greggman** [comment]
thanks for the report.  It should be fixed. You probably need to clear your cache go maybe [go here](https://webgl2fundamentals.org/webgl/resources/editor.js), refresh that, and then maybe the other pages will work.

**Comment by mohawk2** [comment]
I think this is fixed, so this could be closed?
